config/routes.rb
Rails.application.routes.draw do
 


  devise_for :users
    resources :patients do
      	resources :corevaluations
        resources :actual_diseases
        resources :actual_hepatics
        resources :antecedent_hepatics
        resources :antecedents
        resources :complementarios_exams
        resources :examen_fisicos
        resources :farmacologico_treatments
        resources :laboratory_exams
        
  end


  
  get 'static_pages/protocolos', to: "static_pages#protocolos"

  get 'static_pages/home', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'static_pages/about', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'patients/new', to: "patients#new"

 

  root to: "static_pages#home"

#  root "patients#index"

end

  

app/models/actual_disease.rb
class ActualDisease < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/actual_hepatic.rb
class ActualHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent.rb
class Antecedent < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent_hepatic.rb
class AntecedentHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/complementarios_exam.rb
class ComplementariosExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/corevaluation.rb
class Corevaluation < ActiveRecord::Base
belongs_to :patient
belongs_to :user

end

app/models/examen_fisico.rb
class ExamenFisico < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/farmacologico_treatment.rb
class FarmacologicoTreatment < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/laboratory_exam.rb
class LaboratoryExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :users
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams
	has_many :patients
  		devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/corevaluations_controller.rb
class CorevaluationsController < ApplicationController

	before_action :find_patient
	before_action :find_corevaluation, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
	@corevaluation = Corevaluation.new
	end


	def create
	@corevaluation = Corevaluation.new(corevaluation_params)
	@corevaluation.patient_id = @patient.id
	@corevaluation.user_id = current_user.id
	
		if @corevaluation.save
			redirect_to patient_path(@patient)
		else
			render 'new'
		end	
	end

	def edit
	end
	
	def update
	
		if @corevaluation.update(corevaluation_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
				
		end	
	
		def destroy
			@corevaluation.destroy
			redirect_to patient_path(@patient)
		end

	end

		private

			def corevaluation_params
				params.require(:corevaluation).permit(:causa_hepatopatia, :peso, :talla, :pxif, :meld, :melde, :child, :asa, :maximos_riesgos, :ingresa_lista, :causa_no_ingreso, :estudios_pendientes, :candidato_fastrack, :candidato_tranexamico)
			end

			def find_patient
				@patient = Patient.find(params[:patient_id])
			end

			def find_corevaluation
				@corevaluation = Corevaluation.find(params[:id])
				
			end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

before_action :find_patient, only: [:show, :edit, :update, :destroy]


	def index
		@q = Patient.ransack(params[:q].try(:merge, m: 'or'))
		@patients = @q.result
			#@patients = Patient.all.order("created_at DESC")
    end

	def show
	
	end

	def new
		@patient= current_user.patients.build
	end

	def create
		@patient = current_user.patients.build(patient_params)

		if @patient.save
			redirect_to root_path
		else
			render 'new'
		end

	end

	def edit
	end

	def update

		if @patient.update(patient_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
		end
	end


	def destroy

		@patient.destroy
		redirect_to root_path

	end


	private

		def patient_params
			params.require(:patient).permit(:id, :nombre, :apellido, :ci, :fnr, :sexo, :f_nacimiento, :f_ingreso, :prestador, :procedencia, :comentarios)
		end

		def find_patient
			@patient = Patient.find(params[:id])
		end
end

app/helpers/actual_diseases_helper.rb
module ActualDiseasesHelper
end

app/helpers/actual_hepatics_helper.rb
module ActualHepaticsHelper
end

app/helpers/antecedents_helper.rb
module AntecedentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Trasplante Hepatico"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/corevaluations_helper.rb
module CorevaluationsHelper
end

app/helpers/examen_fisicos_helper.rb
module ExamenFisicosHelper
end

app/helpers/laboratory_exams_helper.rb
module LaboratoryExamsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corevaluations/_corevaluation.html.erb
  <ul class="list-inline">
    <li>
      <h4>
        <p class="text-left"> Evaluación Preoperatoria realizada el <%= corevaluation.updated_at %></p>
      </h4>
    </li>
    <li>
       Evaluado por <%= corevaluation.user_id %>
    </li>
  </ul>

  <table class="responsive-table", class="striped">

    <thead>
    <tr>
      <th>Causa hepatopatia:</th>
      <th>Pxif:</th>
      <th>Meld:</th>
      <th>Melde:</th>
      <th>Child:</th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= corevaluation.causa_hepatopatia %></td>
        <td> <%= corevaluation.pxif %></td>
        <td><%= corevaluation.meld %></td>
        <td> <%= corevaluation.melde %></td>
        <td><%= corevaluation.child %></td>
       </tr>
    </tbody>
   <thead>
    <tr>
      <th>Asa:</th>
     <th>Maximos riesgos:</th>
     <th>Ingresa lista:</th>
     <th>Causa no ingreso</th>
     <th>Estudios pendietes ingreso:</th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= corevaluation.asa %></td>
        <td> <%= corevaluation.maximos_riesgos %></td>
        <td> <%= corevaluation.ingresa_lista %></td>
        <td><%= corevaluation.causa_no_ingreso %></td>
        <td><%= corevaluation.estudios_pendientes %></td>
      </tr>
    </tbody>

    <thead>
    <tr>
     <th>Candidato fastrack:</th>
     <th>Candidato tranexamico:</th>
    </tr>
    </thead>


    <tbody>
      <tr>
        <td><%= corevaluation.candidato_fastrack %></td>
        <td><%= corevaluation.candidato_tranexamico %></td>
      </tr>
    </tbody>

  </table>


<% if user_signed_in? %>

    <% if corevaluation.user_id == current_user.id %>

      <div class="links btn-group">

        <%= link_to "Editar", edit_patient_corevaluation_path(corevaluation.patient, corevaluation), class: "btn btn-custom" %>
        <%= link_to "Eliminar", patient_corevaluation_path(corevaluation.patient, corevaluation), method: :delete, data: {confirm: "Esta seguro ?"}, class: "btn btn-custom" %>
 
      </div>
    
    <% end %> 

  <% end %>

app/views/corevaluations/_form.html.erb
<div class container>      
            <%= form_for ([@patient, @patient.corevaluations.build]) do |f| %>
                            
              <div>
              Causa de la Hepatopatia
                  <%= f.select(:causa_hepatopatia, options_for_select(['Sin aclarar','Alcoholica', 'Autoinmune', 'Cirrosis Biliar Primaria', 'Cirrosis Biliar Secundaria', 'Hepatitis B']), {}, {class: "form-control"}) %>
              </div>

              <div>
              Peso actual
                <%= f.number_field :peso %>
              </div>
              <div class="field">
              Talla
                <%= f.number_field :talla %>
              </div>
              <div>
              Pxif
                <%= f.number_field :pxif %>
              </div>
              <div>
              MELD
                <%= f.number_field :meld %>
              </div>
              <div>
              MELDE
                <%= f.number_field :melde %>
              </div>
              <div>
              CHILD
                  <%= f.select(:child, options_for_select(['Sin clasificar','A','B', 'C']), {}, {class: "form-control"}) %>
              </div>
              <div>
              ASA 
                 <%= f.select(:asa, options_for_select(['I','II', 'III', 'IV']), {}, {class: "form-control"}) %>
              </div>
              <div>
              Máximos riesgos
                <%= f.text_area :maximos_riesgos %>
              </div>
              <div>
           
                <%= f.check_box :ingresa_lista %>
                <input type="checkbox" id="ingresa_lista" />
                <label for="ingresa_lista">Ingresa a lista de Trasplante?</label>

              </div>
              <div>
              Causa de no ingreso
                <%= f.text_field :causa_no_ingreso %>
              </div>
              <div>
              Estudios pendientes para el ingreso
                <%= f.text_area :estudios_pendientes %>
              </div>
              <div>
                <input type="checkbox" id="candidato_fastrack" />
                <label for="candidato_fastrack">Candidato a Fast Track?</label>

              </div>
              <div>
            
                <input type="checkbox" id="candidato_tranexamico" />
                <label for="candidato_tranexamico">Candidato a Protocolo de Tranexamico?</label>

              </div>
              <div>
                <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
                <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
              </div>
            <% end %>
</div>

 

<script scr="js/jquery.min.js">
</script>
<script scr="js/materialize.min.js">
</script>

<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>

<script>
$('#textarea1').val('New Text');
</script>

<script>
$('#textarea1').trigger('autoresize');
</script>

<script>
    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 90 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/corevaluations/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>Editar Datos Generales de la evaluacion del paciente</h1>

<%= simple_form_for ([@patient, @corevaluation]) do |f| %>
  
    
	  <div>
              Causa de la Hepatopatia
                  <%= f.select(:causa_hepatopatia, options_for_select(['Sin aclarar','Alcoholica', 'Autoinmune', 'Cirrosis Biliar Primaria', 'Cirrosis Biliar Secundaria', 'Hepatitis B']), {}, {class: "form-control"}) %>
              </div>

              <div>
              Peso actual
                <%= f.number_field :peso %>
              </div>
              <div class="field">
              Talla
                <%= f.number_field :talla %>
              </div>
              <div>
              Pxif
                <%= f.number_field :pxif %>
              </div>
              <div>
              MELD
                <%= f.number_field :meld %>
              </div>
              <div>
              MELDE
                <%= f.number_field :melde %>
              </div>
              <div>
              CHILD
                  <%= f.select(:child, options_for_select(['Sin clasificar','A','B', 'C']), {}, {class: "form-control"}) %>
              </div>
              <div>
              ASA 
                 <%= f.select(:asa, options_for_select(['I','II', 'III', 'IV']), {}, {class: "form-control"}) %>
              </div>
              <div>
              Máximos riesgos
                <%= f.text_area :maximos_riesgos %>
              </div>
              <div>
           
                <%= f.check_box :ingresa_lista %>
                <input type="checkbox" id="ingresa_lista" />
                <label for="ingresa_lista">Ingresa a lista de Trasplante?</label>

              </div>
              <div>
              Causa de no ingreso
                <%= f.text_field :causa_no_ingreso %>
              </div>
              <div>
              Estudios pendientes para el ingreso
                <%= f.text_area :estudios_pendientes %>
              </div>
              <div>
                <input type="checkbox" id="candidato_fastrack" />
                <label for="candidato_fastrack">Candidato a Fast Track?</label>

              </div>
              <div>
            
                <input type="checkbox" id="candidato_tranexamico" />
                <label for="candidato_tranexamico">Candidato a Protocolo de Tranexamico?</label>

              </div>
              <div>
                <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
                <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
              </div>

<% end %>

</div>

app/views/corevaluations/new.html.erb
<class container>
<h1>Ingresar datos generales de la evaluacion preoperatoria</h1>

<%= render 'form' %>