config/routes.rb
Rails.application.routes.draw do
 


  devise_for :users
    resources :patients do
      	resources :corevaluations
        resources :actual_diseases
        resources :actual_hepatics
        resources :antecedent_hepatics
        resources :antecedents
        resources :complementarios_exams
        resources :examen_fisicos
        resources :farmacologico_treatments
        resources :laboratory_exams
        
  end


  
  get 'static_pages/protocolos', to: "static_pages#protocolos"

  get 'static_pages/home', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'static_pages/about', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'patients/new', to: "patients#new"

 

  root to: "static_pages#home"

#  root "patients#index"

end

  

app/models/actual_disease.rb
class ActualDisease < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/actual_hepatic.rb
class ActualHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent.rb
class Antecedent < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent_hepatic.rb
class AntecedentHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/complementarios_exam.rb
class ComplementariosExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/corevaluation.rb
class Corevaluation < ActiveRecord::Base
belongs_to :patient
belongs_to :user

end

app/models/examen_fisico.rb
class ExamenFisico < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/farmacologico_treatment.rb
class FarmacologicoTreatment < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/laboratory_exam.rb
class LaboratoryExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :users
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams
	has_many :patients
  		devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/examen_fisicos_controller.rb
class ExamenFisicosController < ApplicationController
	before_action :find_patient
	before_action :find_examen_fisico, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
	@examen_fisico = ExamenFisico.new
	end


	def create
	@examen_fisico = ExamenFisico.new(examen_fisico_params)
	@examen_fisico.patient_id = @patient.id
	@examen_fisico.user_id = current_user.id
	
		if @examen_fisico.save
			redirect_to patient_path(@patient)
		else
			render 'new'
		end	
	end

	def edit
	end
	
	def update
	
		if @examen_fisico.update(examen_fisico_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
				
		end	
	
		def destroy
			@examen_fisico.destroy
			redirect_to patient_path(@patient)
		end

	end

		private

			def examen_fisico_params
				params.require(:examen_fisico).permit(:apertura_bucal, :mtp, :protesis, :cuello, :pa_sistolica, :fc, :soplos, :pp, :tiroides, :reperes_vvc, :red_venosa, :test_allen, :siquismo, :flapping, :estado_nutricional, :comentarios)
			end

			def find_patient
				@patient = Patient.find(params[:patient_id])
			end

			def find_examen_fisico
				@examen_fisico = ExamenFisico.find(params[:id])
				
			end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

before_action :find_patient, only: [:show, :edit, :update, :destroy]


	def index
		@q = Patient.ransack(params[:q].try(:merge, m: 'or'))
		@patients = @q.result
			#@patients = Patient.all.order("created_at DESC")
    end

	def show
	
	end

	def new
		@patient= current_user.patients.build
	end

	def create
		@patient = current_user.patients.build(patient_params)

		if @patient.save
			redirect_to root_path
		else
			render 'new'
		end

	end

	def edit
	end

	def update

		if @patient.update(patient_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
		end
	end


	def destroy

		@patient.destroy
		redirect_to root_path

	end


	private

		def patient_params
			params.require(:patient).permit(:id, :nombre, :apellido, :ci, :fnr, :sexo, :f_nacimiento, :f_ingreso, :prestador, :procedencia, :comentarios)
		end

		def find_patient
			@patient = Patient.find(params[:id])
		end
end

app/helpers/actual_diseases_helper.rb
module ActualDiseasesHelper
end

app/helpers/actual_hepatics_helper.rb
module ActualHepaticsHelper
end

app/helpers/antecedents_helper.rb
module AntecedentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Trasplante Hepatico"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/corevaluations_helper.rb
module CorevaluationsHelper
end

app/helpers/examen_fisicos_helper.rb
module ExamenFisicosHelper
end

app/helpers/laboratory_exams_helper.rb
module LaboratoryExamsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/examen_fisicos/_examen_fisico.html.erb
  <ul class="list-inline">
    <li>
      <h4>
        <p class="text-left"> Evaluación Preoperatoria realizada el <%= examen_fisico.updated_at %></p>
      </h4>
    </li>
    <li>
       Evaluado por <%= examen_fisico.user_id %>
    </li>
  </ul>

  <table class="responsive-table", class="striped">

    <thead>
    <tr>
      <th>Apertura Bucal</th>
      <th>MPT</th>
      <th>Protesis</th>
      <th>Cuello</th>
      <th>PA Sistolica</th>

    </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= examen_fisico.apertura_bucal %></td>
        <td> <%= examen_fisico.mpt %></td>
        <td><%= examen_fisico.protesis %></td>
        <td> <%= examen_fisico.cuello %></td>
        <td><%= examen_fisico.pa_sistolica %></td>
       </tr>
    </tbody>
   <thead>
    <tr>
      <th>PA Diastolica</th>
      <th>FC</th>
      <th>Soplos</th>
      <th>PP</th>
     <th>Tiroides</th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= examen_fisico.pa_diastolica %></td>
        <td><%= examen_fisico.fc %></td>
        <td> <%= examen_fisico.soplos %></td>
        <td> <%= examen_fisico.pp %></td>
        <td> <%= examen_fisico.tiroides %></td>
      </tr>
    </tbody>
   <thead>
    <tr>
     <th>Reperes VVC<th>
     <th>Red Venosa</th>
     <th>Test Allen</th>
     <th>Siquismo</th>
     <th>Flapping</th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td> <%= examen_fisico.reperes_vvc %></td>
        <td><%= examen_fisico.red_venosa %></td>
        <td><%= examen_fisico.test_allen %></td>
        <td><%= examen_fisico.siquismo %></td>
        <td><%= examen_fisico.flapping %></td>

   <thead>
    <tr>
     <th>Estado Nutricional</th>
     <th>Comentarios</th>
    <tbody>
      <tr>
        <td> <%= examen_fisico.estado_nutricional %></td>
        <td> <%= examen_fisico.comentarios %></td>
      </tr>
    </tbody>



  </table>


<% if user_signed_in? %>

    <% if examen_fisico.user_id == current_user.id %>

      <div class="links btn-group">

        <%= link_to "Editar", edit_patient_examen_fisico_path(examen_fisico.patient, examen_fisico), class: "btn btn-custom" %>
        <%= link_to "Eliminar", patient_examen_fisico_path(examen_fisico.patient, examen_fisico), method: :delete, data: {confirm: "Esta seguro ?"}, class: "btn btn-custom" %>
 
      </div>
    
    <% end %> 

  <% end %>

app/views/examen_fisicos/_form.html.erb
  <div class container>  
  
    <%= form_for ([@patient, @patient.examen_fisicos.build]) do |f| %>
                            
  
      <div>
         Apertura Bucal
         <%= f.select(:apertura_bucal, options_for_select(['Normal','Menor a 3 cm', 'Otras alteraciones']), {}, {class: "form-control"}) %>
      </div>

      <div>
         MPT
         <%= f.select(:mpt, options_for_select(['1','2', '3', '4']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Protesis
         <%= f.select(:protesis, options_for_select(['No','Protesis Superior','Protesis Inferior', 'Protesis Completa', 'Anodoncia sin protesis', 'Diente centinela']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Cuello
         <%= f.select(:cuello, options_for_select(['Sin limitacion flexoextension','Limitación 1/3', 'Limitacion 2/3', 'Limitacion > 2/3', 'Otras alteraciones']), {}, {class: "form-control"}) %>
      </div>

      <div>
        PA Sistolica
        <%= f.number_field :pa_sistolica %>
      </div>

      <div>
        PA Diastolica
        <%= f.number_field :pa_diastolica %>
      </div>

      <div>
        FC
        <%= f.number_field :fc %>
      </div>

      <div>
        <input type="checkbox" id="soplos" />
        <label for="soplos">Soplos?</label>
      </div>

      <div>
         PP
         <%= f.select(:pp, options_for_select(['Normal','Broncoespasmo', 'Derrame Pleural', 'Neumotorax', 'Hemotorax', 'Neumonia', 'Edema Pulmonar', 'SDRA', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Tiroides
         <%= f.select(:tiroides, options_for_select(['Normal','Bocio Difuso', 'Nodulo Toroideo', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Reperes VVC
         <%= f.select(:reperes_vvc, options_for_select(['Buenos','Aceptables', 'Malos', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Red Venosa
         <%= f.select(:red_venosa, options_for_select(['Buena','Aceptable', 'Mala', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Test Allen
         <%= f.select(:test_allen, options_for_select(['Normal','Patologico a Derecha', 'Patologico a Izquierda']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Siquismo
         <%= f.select(:siquismo, options_for_select(['Normal','Patologia Siquiatrica', 'Encefalopatia Hepatica', 'Depresion', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
        <input type="checkbox" id="flapping" />
        <label for="flapping">Flapping?</label>
      </div>

      <div>
         Estado Nutricional
         <%= f.select(:estado_nutricional, options_for_select(['Normal','Desnutricion Leve', 'Desnutricion Moderada', 'Desnutricion Severa', 'Sobrepeso', 'Obesidad Grado I', 'Obesidad Grado II', 'Obesidad Grado III (Morbida)']), {}, {class: "form-control"}) %>
      </div>


      <div class="field">
        <%= f.label 'Comentarios' %><br>
        <%= f.text_area :comentarios %>
      </div>


      <div>
         <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
         <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
      </div>
    <% end %>

 </div>

<script scr="js/jquery.min.js">
</script>
<script scr="js/materialize.min.js">
</script>

<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>

<script>
$('#textarea1').val('New Text');
</script>

<script>
$('#textarea1').trigger('autoresize');
</script>

<script>
    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 90 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/examen_fisicos/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>Editar Examen Fisico</h1>


  <div class container>  
  
    <%= form_for ([@patient, @patient.examen_fisicos.build]) do |f| %>
                            
  
      <div>
         Apertura Bucal
         <%= f.select(:apertura_bucal, options_for_select(['Normal','Menor a 3 cm', 'Otras alteraciones']), {}, {class: "form-control"}) %>
      </div>

      <div>
         MPT
         <%= f.select(:mpt, options_for_select(['1','2', '3', '4']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Protesis
         <%= f.select(:protesis, options_for_select(['No','Protesis Superior','Protesis Inferior', 'Protesis Completa', 'Anodoncia sin protesis', 'Diente centinela']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Cuello
         <%= f.select(:cuello, options_for_select(['Sin limitacion flexoextension','Limitación 1/3', 'Limitacion 2/3', 'Limitacion > 2/3', 'Otras alteraciones']), {}, {class: "form-control"}) %>
      </div>

      <div>
        PA Sistolica
        <%= f.number_field :pa_sistolica %>
      </div>

      <div>
        PA Diastolica
        <%= f.number_field :pa_diastolica %>
      </div>

      <div>
        FC
        <%= f.number_field :fc %>
      </div>

      <div>
        <input type="checkbox" id="soplos" />
        <label for="soplos">Soplos?</label>
      </div>

      <div>
         PP
         <%= f.select(:pp, options_for_select(['Normal','Broncoespasmo', 'Derrame Pleural', 'Neumotorax', 'Hemotorax', 'Neumonia', 'Edema Pulmonar', 'SDRA', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Tiroides
         <%= f.select(:tiroides, options_for_select(['Normal','Bocio Difuso', 'Nodulo Toroideo', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Reperes VVC
         <%= f.select(:reperes_vvc, options_for_select(['Buenos','Aceptables', 'Malos', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Red Venosa
         <%= f.select(:red_venosa, options_for_select(['Buena','Aceptable', 'Mala', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Test Allen
         <%= f.select(:test_allen, options_for_select(['Normal','Patologico a Derecha', 'Patologico a Izquierda']), {}, {class: "form-control"}) %>
      </div>

      <div>
         Siquismo
         <%= f.select(:siquismo, options_for_select(['Normal','Patologia Siquiatrica', 'Encefalopatia Hepatica', 'Depresion', 'Otros hallazgos']), {}, {class: "form-control"}) %>
      </div>

      <div>
        <input type="checkbox" id="flapping" />
        <label for="flapping">Flapping?</label>
      </div>

      <div>
         Estado Nutricional
         <%= f.select(:estado_nutricional, options_for_select(['Normal','Desnutricion Leve', 'Desnutricion Moderada', 'Desnutricion Severa', 'Sobrepeso', 'Obesidad Grado I', 'Obesidad Grado II', 'Obesidad Grado III (Morbida)']), {}, {class: "form-control"}) %>
      </div>


      <div class="field">
        <%= f.label 'Comentarios' %><br>
        <%= f.text_area :comentarios %>
      </div>


      <div>
         <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
         <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
      </div>
      </div>
    <% end %>

 </div>



<script scr="js/jquery.min.js">
</script>
<script scr="js/materialize.min.js">
</script>

<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>

<script>
$('#textarea1').val('New Text');
</script>

<script>
$('#textarea1').trigger('autoresize');
</script>

<script>
    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 90 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/examen_fisicos/new.html.erb
<class container>
<h1>Ingresar Tratamiento Farmacologico Actual</h1>

<%= render 'form' %>