config/routes.rb
Rails.application.routes.draw do
 


  devise_for :users
    resources :patients do
      	resources :corevaluations
        resources :actual_diseases
        resources :actual_hepatics
        resources :antecedent_hepatics
        resources :antecedents
        resources :complementarios_exams
        resources :examen_fisicos
        resources :farmacologico_treatments
        resources :laboratory_exams
        
  end


  
  get 'static_pages/protocolos', to: "static_pages#protocolos"

  get 'static_pages/home', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'static_pages/about', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'patients/new', to: "patients#new"

 

  root to: "static_pages#home"

#  root "patients#index"

end

  

app/models/actual_disease.rb
class ActualDisease < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/actual_hepatic.rb
class ActualHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent.rb
class Antecedent < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent_hepatic.rb
class AntecedentHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/complementarios_exam.rb
class ComplementariosExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/corevaluation.rb
class Corevaluation < ActiveRecord::Base
belongs_to :patient
belongs_to :user

end

app/models/examen_fisico.rb
class ExamenFisico < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/farmacologico_treatment.rb
class FarmacologicoTreatment < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/laboratory_exam.rb
class LaboratoryExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :users
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams
	has_many :patients
  		devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/complementarios_exams_controller.rb
class ComplementariosExamsController < ApplicationController
	before_action :find_patient
	before_action :find_complementarios_exam, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
	@complementarios_exam = ComplementariosExam.new
	end


	def create
	@complementarios_exam = ComplementariosExam.new(complementarios_exam_params)
	@complementarios_exam.patient_id = @patient.id
	@complementarios_exam.user_id = current_user.id
	
		if @complementarios_exam.save
			redirect_to patient_path(@patient)
		else
			render 'new'
		end	
	end

	def edit
	end
	
	def update
	
		if @complementarios_exam.update(complementarios_exam_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
				
		end	
	
		def destroy
			@complementarios_exam.destroy
			redirect_to patient_path(@patient)
		end

	end

		private

			def complementarios_exam_params
				params.require(:complementarios_exam).permit(:ecg, :ecocardiograma, :ecodobutamina, :ergometria, :holer, :rxtx, :funcional_respiratorio, :comentarios)
			end

			def find_patient
				@patient = Patient.find(params[:patient_id])
			end

			def find_complementarios_exam
				@complementarios_exam = ComplementariosExam.find(params[:id])
				
			end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

before_action :find_patient, only: [:show, :edit, :update, :destroy]


	def index
		@q = Patient.ransack(params[:q].try(:merge, m: 'or'))
		@patients = @q.result
			#@patients = Patient.all.order("created_at DESC")
    end

	def show
	
	end

	def new
		@patient= current_user.patients.build
	end

	def create
		@patient = current_user.patients.build(patient_params)

		if @patient.save
			redirect_to root_path
		else
			render 'new'
		end

	end

	def edit
	end

	def update

		if @patient.update(patient_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
		end
	end


	def destroy

		@patient.destroy
		redirect_to root_path

	end


	private

		def patient_params
			params.require(:patient).permit(:id, :nombre, :apellido, :ci, :fnr, :sexo, :f_nacimiento, :f_ingreso, :prestador, :procedencia, :comentarios)
		end

		def find_patient
			@patient = Patient.find(params[:id])
		end
end

app/helpers/actual_diseases_helper.rb
module ActualDiseasesHelper
end

app/helpers/actual_hepatics_helper.rb
module ActualHepaticsHelper
end

app/helpers/antecedents_helper.rb
module AntecedentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Trasplante Hepatico"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/complementarios_exams_helper.rb
module ComplementariosExamsHelper
end

app/helpers/corevaluations_helper.rb
module CorevaluationsHelper
end

app/helpers/examen_fisicos_helper.rb
module ExamenFisicosHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/complementarios_exams/_complementarios_exam.html.erb
  <ul class="list-inline">
    <li>
      <h4>
        <p class="text-left"> Evaluación Preoperatoria realizada el <%= complementarios_exam.updated_at %></p>
      </h4>
    </li>
    <li>
       Evaluado por <%= complementarios_exam.user_id %>
    </li>
  </ul>

  <table class="responsive-table", class="striped">

    <thead>
    <tr>
      <th>ECG</th>
      <th>Ecocardiograma Basal</th>
      <th>Eco Dobutamina</th>
      <th>PEG</th>

    </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= complementarios_exam.ecg %></td>
        <td> <%= complementarios_exam.ecocardiograma %></td>
        <td><%= complementarios_exam.ecodobutamina %></td>
        <td> <%= complementarios_exam.ergometria %></td>
       </tr>
    </tbody>
   <thead>
    <tr>
     <th>Holter</th>
     <th>RxTx</th>
     <th>Funcional Respiratorio</th>
     <th>Comentarios<th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= complementarios_exam.holter %></td>
        <td> <%= complementarios_exam.rxtx %></td>
        <td><%= complementarios_exam.funcional_respiratorio %></td>
        <td><%= complementarios_exam.comentarios %></td>
      </tr>
    </tbody>
  </table>


<% if user_signed_in? %>

    <% if complementarios_exam.user_id == current_user.id %>

      <div class="links btn-group">

        <%= link_to "Editar", edit_patient_complementarios_exam_path(complementarios_exam.patient, complementarios_exam), class: "btn btn-custom" %>
        <%= link_to "Eliminar", patient_complementarios_exam_path(complementarios_exam.patient, complementarios_exam), method: :delete, data: {confirm: "Esta seguro ?"}, class: "btn btn-custom" %>
 
      </div>
    
    <% end %> 

  <% end %>

app/views/complementarios_exams/_form.html.erb
  <div class container> 
    
  <%= form_for ([@patient, @patient.complementarios_exams.build]) do |f| %>
                            
  <div>
    ECG
    <%= f.select(:ecg, options_for_select(['No realizado','Normal','Bloqueo de Rama Izquierda', 'Bloqueo Rama Derecha', 'Bloqueo AV 1er grado', 'Bloqueo AV 2o grado', 'Bloqueo AV completo', 'Secuela IAM']), {}, {class: "form-control"}) %>
  </div>

  <div>
    Ecocardiograma
    <%= f.select(:ecocardiograma, options_for_select(['No realizado','Normal', 'HVI', 'Alteraciones sectoriales de la contractilidad', 'FEVI < 40%', 'FEVI < 30%', 'Otras alteraciones']), {}, {class: "form-control"}) %>
  </div>
  <div>
    Eco Dobutamina
    <%= f.select(:ecodobutamina, options_for_select(['No realizado','Negativo para Isquemia','Positivo para Isquemia']), {}, {class: "form-control"}) %>
  </div>
  <div>
    PEG
    <%= f.select(:ergometria, options_for_select(['No realizado','Negativo para Isquemia','Positivo para Isquemia', 'No concluyente']), {}, {class: "form-control"}) %>
  </div>
  <div>
    Holter
    <%= f.select(:holter, options_for_select(['No realizado','Normal','Patologico']), {}, {class: "form-control"}) %>
  </div>
  <div>
    RxTx
    <%= f.select(:rxtx, options_for_select(['No realizado','Normal','Patológica']), {}, {class: "form-control"}) %>
  </div>
  <div>
    Funcional Respiratorio
    <%= f.select(:funcional_respiratorio, options_for_select(['No realizado','Obstructivo leve','Obstructivo Moderado', 'Obstructivo Severo', 'Restrictivo leve', 'Restrictivo Moderado', 'Restrictivo Severo', 'Patrón mixto leve', 'Patron mixto moderado', 'Patrón mixto Severo']), {}, {class: "form-control"}) %>
  </div>
  <div class="field">
    <%= f.label 'Comentarios' %><br>
    <%= f.text_area :comentarios %>
              <div>
                <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
                <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
              </div>
  <% end %>
</div>


<script scr="js/jquery.min.js">
</script>
<script scr="js/materialize.min.js">
</script>

<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>

<script>
$('#textarea1').val('New Text');
</script>

<script>
$('#textarea1').trigger('autoresize');
</script>

<script>
    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 90 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/complementarios_exams/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>Editar Examenes Complementarios</h1>

<%= simple_form_for ([@patient, @complementarios_exam]) do |f| %>
  

   <div>
    ECG
    <%= f.select(:ecg, options_for_select(['No realizado','Normal','Bloqueo de Rama Izquierda', 'Bloqueo Rama Derecha', 'Bloqueo AV 1er grado', 'Bloqueo AV 2o grado', 'Bloqueo AV completo', 'Secuela IAM']), {}, {class: "form-control"}) %>
  </div>

  <div>
    Ecocardiograma
    <%= f.select(:ecocardiograma, options_for_select(['No realizado','Normal', 'HVI', 'Alteraciones sectoriales de la contractilidad', 'FEVI < 40%', 'FEVI < 30%', 'Otras alteraciones']), {}, {class: "form-control"}) %>
  </div>
  <div>
    Eco Dobutamina
    <%= f.select(:ecodobutamina, options_for_select(['No realizado','Negativo para Isquemia','Positivo para Isquemia']), {}, {class: "form-control"}) %>
  </div>
  <div>
    PEG
    <%= f.select(:ergometria, options_for_select(['No realizado','Negativo para Isquemia','Positivo para Isquemia', 'No concluyente']), {}, {class: "form-control"}) %>
  </div>
  <div>
    Holter
    <%= f.select(:holter, options_for_select(['No realizado','Normal','Patologico']), {}, {class: "form-control"}) %>
  </div>
  <div>
    RxTx
    <%= f.select(:rxtx, options_for_select(['No realizado','Normal','Patológica']), {}, {class: "form-control"}) %>
  </div>
  <div>
    Funcional Respiratorio
    <%= f.select(:funcional_respiratorio, options_for_select(['No realizado','Obstructivo leve','Obstructivo Moderado', 'Obstructivo Severo', 'Restrictivo leve', 'Restrictivo Moderado', 'Restrictivo Severo', 'Patrón mixto leve', 'Patron mixto moderado', 'Patrón mixto Severo', '']), {}, {class: "form-control"}) %>
  </div>
  <div class="field">
    <%= f.label 'Comentarios' %><br>
    <%= f.text_area :comentarios %>
              <div>
                <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
                <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
              </div>

<% end %>


</div>


<script scr="js/jquery.min.js">
</script>
<script scr="js/materialize.min.js">
</script>

<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>

<script>
$('#textarea1').val('New Text');
</script>

<script>
$('#textarea1').trigger('autoresize');
</script>

<script>
    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 90 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/complementarios_exams/new.html.erb
<class container>
<h1>Ingresar Examenes Complementarios</h1>

<%= render 'form' %>