config/routes.rb
Rails.application.routes.draw do
 


  devise_for :users
    resources :patients do
      	resources :corevaluations
        resources :actual_diseases
        resources :actual_hepatics
        resources :antecedent_hepatics
        resources :antecedents
        resources :complementarios_exams
        resources :examen_fisicos
        resources :farmacologico_treatments
        resources :laboratory_exams
        
  end


  
  get 'static_pages/protocolos', to: "static_pages#protocolos"

  get 'static_pages/home', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'static_pages/about', to: "static_pages#about"

  get 'static_pages/help', to: "static_pages#help"

  get 'patients/new', to: "patients#new"

 

  root to: "static_pages#home"

#  root "patients#index"

end

  

app/models/actual_disease.rb
class ActualDisease < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/actual_hepatic.rb
class ActualHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent.rb
class Antecedent < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/antecedent_hepatic.rb
class AntecedentHepatic < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/complementarios_exam.rb
class ComplementariosExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/corevaluation.rb
class Corevaluation < ActiveRecord::Base
belongs_to :patient
belongs_to :user

end

app/models/examen_fisico.rb
class ExamenFisico < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/farmacologico_treatment.rb
class FarmacologicoTreatment < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/laboratory_exam.rb
class LaboratoryExam < ActiveRecord::Base
belongs_to :patient
belongs_to :user
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :users
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :corevaluations
	has_many :actual_diseases
	has_many :actual_hepatics
	has_many :antecedent_hepatics
	has_many :antecedents
	has_many :complementarios_exams
	has_many :examen_fisicos
	has_many :farmacologico_treatments
	has_many :laboratory_exams
	has_many :patients
  		devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/laboratory_exams_controller.rb
class LaboratoryExamsController < ApplicationController
	before_action :find_patient
	before_action :find_laboratory_exam, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
	@laboratory_exam = LaboratoryExam.new
	end


	def create
	@laboratory_exam = LaboratoryExam.new(laboratory_exam_params)
	@laboratory_exam.patient_id = @patient.id
	@laboratory_exam.user_id = current_user.id
	
		if @laboratory_exam.save
			redirect_to patient_path(@patient)
		else
			render 'new'
		end	
	end

	def edit
	end
	
	def update
	
		if @laboratory_exam.update(laboratory_exam_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
				
		end	
	
		def destroy
			@laboratory_exam.destroy
			redirect_to patient_path(@patient)
		end

	end

		private

			def laboratory_exam_params
				params.require(:laboratory_exam).permit(:hb, :hto, :plaquetas, :gb, :tp, :inr, :fibrinogeno, :aPTT, :glicemia, :azoemia, :creatininemia, :na, :k, :albumina, :proteinas_totales, :fa, :tgo, :tgp, :bt, :bd, :bi, :amilasemia, :hiv, :cmv, :vdrl, :tsh, :fecha_ultima_parac, :comentarios)
			end

			def find_patient
				@patient = Patient.find(params[:patient_id])
			end

			def find_laboratory_exam
				@laboratory_exam = LaboratoryExam.find(params[:id])
				
			end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

before_action :find_patient, only: [:show, :edit, :update, :destroy]


	def index
		@q = Patient.ransack(params[:q].try(:merge, m: 'or'))
		@patients = @q.result
			#@patients = Patient.all.order("created_at DESC")
    end

	def show
	
	end

	def new
		@patient= current_user.patients.build
	end

	def create
		@patient = current_user.patients.build(patient_params)

		if @patient.save
			redirect_to root_path
		else
			render 'new'
		end

	end

	def edit
	end

	def update

		if @patient.update(patient_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
		end
	end


	def destroy

		@patient.destroy
		redirect_to root_path

	end


	private

		def patient_params
			params.require(:patient).permit(:id, :nombre, :apellido, :ci, :fnr, :sexo, :f_nacimiento, :f_ingreso, :prestador, :procedencia, :comentarios)
		end

		def find_patient
			@patient = Patient.find(params[:id])
		end
end

app/helpers/actual_diseases_helper.rb
module ActualDiseasesHelper
end

app/helpers/actual_hepatics_helper.rb
module ActualHepaticsHelper
end

app/helpers/antecedents_helper.rb
module AntecedentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Trasplante Hepatico"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/corevaluations_helper.rb
module CorevaluationsHelper
end

app/helpers/examen_fisicos_helper.rb
module ExamenFisicosHelper
end

app/helpers/laboratory_exams_helper.rb
module LaboratoryExamsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/laboratory_exams/_form.html.erb
  <div class container>  
            <%= form_for ([@patient, @patient.laboratory_exams.build]) do |f| %>
                            
    <div class="field">
      Hb
      <%= f.number_field :hb %>
    </div>

    <div class="field">
      Hto
      <%= f.number_field :hto %>
    </div>

    <div class="field">
      Plaquetas
      <%= f.number_field :plaquetas %>
    </div>

    <div class="field">
      GB
      <%= f.number_field :gb %>
    </div>

    <div class="field">
      TP
      <%= f.number_field :tp %>
    </div>

    <div class="field">
      INR
      <%= f.number_field :inr %>
    </div>

    <div class="field">
      Fibrinogeno
      <%= f.number_field :fibrinogeno %>
    </div>

    <div class="field">
      aPTT
      <%= f.number_field :aPTT %>
    </div>

    <div class="field">
      Glicemia
      <%= f.number_field :glicemia %>
    </div>

    <div class="field">
      Azoemia
      <%= f.number_field :azoemia %>
    </div>

    <div class="field">
      Creatininemia
      <%= f.number_field :creatininemia %>
    </div>

    <div class="field">
      Na
      <%= f.number_field :na %>
    </div>

    <div class="field">
      K
      <%= f.number_field :k %>
    </div>

    <div class="field">
      Albumina
      <%= f.number_field :albumina %>
    </div>

    <div class="field">
      Proteinas Totales
      <%= f.number_field :proteinas_totales %>
    </div>

    <div class="field">
      FA
      <%= f.number_field :fa %>
    </div>

    <div class="field">
      TGO
      <%= f.number_field :tgo %>
    </div>

    <div class="field">
      TGP
      <%= f.number_field :tgp %>
    </div>

    <div class="field">
      BT
      <%= f.number_field :bt %>
    </div>

    <div class="field">
      BD
      <%= f.number_field :bd %>
    </div>


    <div class="field">
      BI
      <%= f.number_field :bi %>
    </div>

    <div class="field">
      Amilasemia
      <%= f.number_field :amilasemia %>
    </div>

    <div class="field">
      TSH
      <%= f.number_field :tsh %>
    </div>

    <div>
      HIV
      <%= f.select(:hiv, options_for_select(['Pendiente','Negativo', 'POSITIVO']), {}, {class: "form-control"}) %>
    </div>

    <div>
      CMV
      <%= f.select(:cmv, options_for_select(['Pendiente','Negativo', 'POSITIVO']), {}, {class: "form-control"}) %>
    </div>

    <div>
      VDRL
      <%= f.select(:vdrl, options_for_select(['Pendiente','Negativo', 'POSITIVO']), {}, {class: "form-control"}) %>
    </div>

    <div>
      Fecha ultima paraclinica
      <input type="date" class="datepicker">
      <%= f.date_select(:fecha_ultima_parac, class: "form-control", placeholder: "Fecha ultima paraclinica") %>
    </div>
  
    <div class="field">
        <%= f.label 'Comentarios' %><br>
        <%= f.text_area :comentarios %>
    </div>


              <div>
                <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
                <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
              </div>
            <% end %>

 </div>

<script scr="js/jquery.min.js">
</script>
<script scr="js/materialize.min.js">
</script>

<script>
  $(document).ready(function() {
    Materialize.updateTextFields();
  });
</script>

<script>
$('#textarea1').val('New Text');
</script>

<script>
$('#textarea1').trigger('autoresize');
</script>

<script>
    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 90 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/laboratory_exams/_laboratory_exam.html.erb
  <ul class="list-inline">
    <li>
      <h4>
        <p class="text-left"> Evaluación Preoperatoria realizada el <%= laboratory_exam.updated_at %></p>
      </h4>
    </li>
    <li>
       Evaluado por <%= laboratory_exam.user_id %>
    </li>
  </ul>

  <table class="responsive-table", class="striped">

    <thead>
    <tr>
      <th>Hb</th>
      <th>Hto</th>
      <th>Plaquetas</th>
      <th>Gb</th>
      <th>TP</th>

    </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= laboratory_exam.hb %></td>
        <td> <%= laboratory_exam.hto %></td>
        <td><%= laboratory_exam.plaquetas %></td>
        <td> <%= laboratory_exam.gb %></td>
        <td><%= laboratory_exam.tp %></td>
       </tr>
    </tbody>
   <thead>
    <tr>
      <th>INR</th>
      <th>Fibrinogeno</th>
      <th>aPTT</th>
      <th>Glicemia</th>
     <th>Azoemia</th>
     </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= laboratory_exam.inr %></td>
        <td> <%= laboratory_exam.fibrinogeno %></td>
        <td><%= laboratory_exam.aPTT %></td>
        <td><%= laboratory_exam.glicemia %></td>
        <td> <%= laboratory_exam.azoemia %></td>
    </tr>
    </tbody>

   <thead>
    <tr>
     <th>Creatininemia<th>
     <th>Na</th>
     <th>K</th>
     <th>Albumina</th>
     <th>Proteinas Totales</th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= laboratory_exam.creatininemia %></td>
        <td><%= laboratory_exam.na %></td>
        <td><%= laboratory_exam.k %></td>
        <td><%= laboratory_exam.albumina %></td>
        <td><%= laboratory_exam.proteinas_totales %></td>
    </tr>
    </tbody>

   <thead>
    <tr>
     <th>FA</th>
     <th>TGO</th>
     <th>TGP</th>
     <th>BT</th>
     <th>BD<th>
    </tr>
   </thead>

    <tbody>
      <tr>
        <td> <%= laboratory_exam.fa %></td>
        <td><%= laboratory_exam.tgo %></td>
        <td><%= laboratory_exam.tgp %></td>
        <td> <%= laboratory_exam.bt %></td>
        <td> <%= laboratory_exam.bd %></td>
      </tr>
    </tbody>


    <thead>
    <tr>
     <th>BI</th>
     <th>Amilasemia</th>
     <th>HIV</th>
     <th>CMV</th>
     <th>VDRL</th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= laboratory_exam.bi %></td>
        <td><%= laboratory_exam.amilasemia %></td>
        <td><%= laboratory_exam.hiv %></td>
        <td><%= laboratory_exam.cmv %></td>
        <td><%= laboratory_exam.vdrl %></td>
      </tr>
    </tbody>

   <thead>
    <tr>
       <th>TSH</th>
       <th>Fecha ultima paraclinica</th>
       <th>Comentarios</th>

    </tr>
   </thead>
    <tbody>
     <tr>
       <td><%= laboratory_exam.tsh %></td>
       <td><%= laboratory_exam.fecha_ultima_parac %></td>
       <td><%= laboratory_exam.comentarios %></td>

     </tr>
    </tbody>

  </table>



<% if user_signed_in? %>

    <% if laboratory_exam.user_id == current_user.id %>

      <div class="links btn-group">

        <%= link_to "Editar", edit_patient_laboratory_exam_path(laboratory_exam.patient, laboratory_exam), class: "btn btn-custom" %>
        <%= link_to "Eliminar", patient_laboratory_exam_path(laboratory_exam.patient, laboratory_exam), method: :delete, data: {confirm: "Esta seguro ?"}, class: "btn btn-custom" %>
 
      </div>
    
    <% end %> 

  <% end %>

app/views/laboratory_exams/edit.html.erb
<div class="col-md-6 col-md-offset-3">

<h1>Editar Examenes de Laboratorio</h1>

<%= simple_form_for ([@patient, @laboratory_exam]) do |f| %>
  

    


    <%= f.input :hb %>
    <%= f.input :hto %>
    <%= f.input :plaquetas %>
    <%= f.input :gb %>
    <%= f.input :tp %>
    <%= f.input :inr %>
    <%= f.input :fibrinogeno %>
    <%= f.input :aPTT %>
    <%= f.input :glicemia %>
    <%= f.input :azoemia %>
    <%= f.input :creatininemia %>
    <%= f.input :na %>
    <%= f.input :k %>
    <%= f.input :albumina %>
    <%= f.input :proteinas_totales %>
    <%= f.input :fa %>
    <%= f.input :tgo %>
    <%= f.input :tgp %>
    <%= f.input :bt %>
    <%= f.input :bd %>
    <%= f.input :bi %>
    <%= f.input :amilasemia %>
    <%= f.input :hiv %>
    <%= f.input :cmv %>
    <%= f.input :vdrl %>
    <%= f.input :tsh %>
    <%= f.input :fecha_ultima_parac %>
    <%= f.input :comentarios %>

      
    <div>
        <%= f.submit('Confirmar', class: 'btn btn-primary') %>|
        <%= link_to 'Atras', patients_path, class: 'btn btn-default' %>
    </div>

<% end %>


</div>

app/views/laboratory_exams/new.html.erb
<class container>
<h1>Ingresar Examenes de Laboratorio</h1>

<%= render 'form' %>